### PR TITLE
Improved readability of README.md

### PR DESCRIPTION
**Pull request by jasdeepgill**
Changed
", if needed project mentors are willing to invest their time in these contributors. If you are unsure what to do then the best way is to make a broken merge request and wait for review and info."

into

". If needed project mentors are willing to invest their time into new contributors. If you are unsure of what to do then the best thing to do is to make a broken merge request and wait for review. The review will help guide you on what to do."

First I split up the first sentence into two as the two parts of the original sentence do not need to be in the same sentence. Giving the second part its own sentence makes it more clear what is being stated. 
The second sentence was improved so that it is clearer what new contributors should do. Also made clear what the review will do.

### CODE REVIEW

**Comment by Kreyren** [comment]
Thanks!

**Comment by jasdeepgill** [comment]
Is there any other documentation on github I should look at to try and improve grammar and readability.

**Comment by Kreyren** [comment]
@jasdeepgill I'm trying to maintain a wiki on https://github.com/Kreytricks/kreytricks/wiki which is composed of the most common questions i get and resources for contribution.

**Comment by jasdeepgill** [comment]
> @jasdeepgill I'm trying to maintain a wiki on https://github.com/Kreytricks/kreytricks/wiki which is composed of the most common questions i get and resources for contribution.

How do I make a commit/pull request for the wiki?

**Comment by Kreyren** [comment]
> How do I make a commit/pull request for the wiki?

Wiki can be edited using GUI on https://github.com/Kreytricks/kreytricks/wiki

image


Everything relevant is welcomed there

**Pull request merged**
